### ISSUE TITLE
How was the data sourced?

### ISSUE THREAD

**Issue by ciri** [TheEconomist/the-economist-war-fire-model#1]
In order to be able to replicate the analysis, it would be great to have more info on how the data was sourced. It's not entirely clear what settings were used to source this one, e.g., 

```
# Source: https://earthdata.nasa.gov/earth-observation-data/near-real-time/firms
fire_raw <- st_read('source-data/2000-2022-03-10/fire_archive_SV-C2_256359.shp')
fire_raw <- rbind(fire_raw, st_read("source-data/2000-2022-03-10/fire_archive_M-C61_256357.shp"))
```

What steps should we follow to obtain this data once we get to the URL? What settings were used?

**Comment by sondreus** [comment]
Hi Ciri,

I've added detailed instructions here: https://github.com/TheEconomist/the-economist-war-fire-model/blob/f400975a4c0a47cb0737b18861bcd3d33ea3a914/scripts/01-construct-training-and-prediction-data.R#L25

Let me know if this solves your issue.

**Comment by cslm1** [comment]
This data source script does not appear to exist in the repo and requires further documentation.

In `scripts/01-construct-training-and-prediction-data.R` line 232

``` r
# 7. Add nightlights data ------------------------------
cat('7. Add nightlights data\n')

# source('scripts/ukraine-fire-get-nightlights-data.R')
nightlights <- readRDS('output-data/nightlights.RDS')
nightlights <- nightlights[nightlights$id %in% X$id, ]
```
Thanks!

**Comment by sondreus** [comment]
Apologies - now added (with updated name). Hope this resolves.

**Comment by sondreus** [comment]
Will close this for now, do re-open if further issues.

**Comment by wmcass** [comment]
Can you add information about how you sourced the shape files from ISW?

**Comment by sondreus** [comment]
Hi @wmcass -- I requested an archive from them and got it as a giant zip.

**Comment by wmcass** [comment]
Got it. Thanks!
