### ISSUE TITLE
File missing output-data/X_matrix.RDS

### ISSUE THREAD

**Issue by ljo3** [TheEconomist/the-economist-war-fire-model#2]
Hello,

Could you please add the missing RDS files into the repository? 

I am trying to 00-main-script.R. It cannot run beyond line 28 `source('scripts/05-war-fire-classifier.R')`. 
The file is looking for two RDS files `output-data/X_mat_with_preds.RDS` and `output-data/X_matrix.RDS`. Both of which are missing in the directory.

**Comment by sondreus** [comment]
Hi,

They are not missing in the sense of being omitted by accident. Rather, these are intermediate files that are generated by acquiring the source data and running the preceding scripts. Intermediate and source files are not part of this repo for two reasons, which are that they would bring the size of the repo beyond Github size limits, and, more importantly, I am not sure that we have the rights to share the source files (or intermediate files containing their data) directly.

Hope this clarifies.

**Comment by ljo3** [comment]
I understand completely. Would you be able to put in some indication of what sort of data (or some file with dummy data) is in the files? Just to be able to run the script? 

Happy to close the issue in any case.
