### ISSUE TITLE
.tif to .RDS cloud file conversion

### ISSUE THREAD

**Issue by wmcass** [TheEconomist/the-economist-war-fire-model#3]
Hi,

Are you converting the .tif files from the google earth engine to .RDS files somewhere? Line 245 of the script "01-construct-training-and-prediction-data.R" seems to imply that you are. See below: 

```
cloud_data <- rbindlist(lapply(processed_cloud_files, FUN = function(i) readRDS(paste0('source-data/cloud-data-processed/', i))), fill = T)
```

I cannot find in the source code where you are doing this. Is there a step that I am missing somewhere? 

Thanks for your time and help!

Best,
Will

**Comment by sondreus** [comment]
Hi Wmcass,

Thank you for pointing this out. I've now added that script to the repo.

https://github.com/TheEconomist/the-economist-war-fire-model/blob/master/scripts/aux_process_cloud_tiffs.R

All the best,
Sondre

**Comment by wmcass** [comment]
Thanks!
