### ISSUE TITLE
Dates missing when running 01-construct-training-and-prediction-data script.

### ISSUE THREAD

**Issue by CoeusAnalysis** [TheEconomist/the-economist-war-fire-model#4]
Thank you ahead for any help you can provide.

When running this script (01-construct-training-and-prediction-data) I error out at the ACQ Date lines:

`fire_raw$week <- week(fire_raw$ACQ_DATE)
fire_raw$month <- month(fire_raw$ACQ_DATE)
fire_raw$year <- year(fire_raw$ACQ_DATE)`

The files don't appear to have a date in them for this to target, the only column the file has is the "geometry" column. Am I using the wrong FIRMS data? I also had trouble with the r bind function and had to swap it out for the bind_rows function instead which worked fine.

**Comment by sondreus** [comment]
Hi,

I think you have the wrong FIRMS data. Mine looks like this: https://raw.githubusercontent.com/TheEconomist/the-economist-war-fire-model/master/source-data/firms_archive_2.csv

All the best, 
Sondre

**Comment by CoeusAnalysis** [comment]
Figured it out, I'm an idiot. 

I needed to include every file type in the source data folder from FIRMS rather than just the SHP and SHX files. That fixed the issue.

Apologies, my inexperience caused this problem. Thank you for helping.

**Comment by sondreus** [comment]
No problem CoeusAnalysis - I've probably made the same mistake at some point
