### ISSUE TITLE
Aren't you exposing sensitive data that could be used by criminals?

### ISSUE THREAD

**Issue by Bessonov** [TheEconomist/the-economist-war-fire-model#5]
Doesn't it lead to more deaths?

**Comment by sondreus** [comment]
Hi,

Our system is based on data that is already openly shared. My judgment has been that I should not presume our analysis of it is better than what those engaged in the conflict have access to already via their intelligence agencies. We have had no official requests for it to be taken down. I hope that our analysis and data can have the opposite effect: that we allow better decisions to be made. At least one major IGO have requested help in how to use the system to brief their leaders, who make decisions about where to send aid.

All that said, I welcome any input on this difficult point.
